# Generated by Django 5.2.1 on 2025-08-08 19:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Deficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve conter 11 dígitos numéricos.', regex='^\\d{11}$')], verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Telefone inválido.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone')),
                ('telefone_responsavel', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Telefone inválido.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone')),
                ('nome', models.CharField(blank=True, max_length=150, verbose_name='Nome completo')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('pronomes', models.CharField(blank=True, max_length=50, verbose_name='Pronomes')),
                ('curriculo_lattes', models.URLField(blank=True, verbose_name='Currículo Lattes')),
                ('documento_cpf', models.BinaryField(blank=True, null=True)),
                ('documento_rg', models.BinaryField(blank=True, null=True)),
                ('foto', models.BinaryField(blank=True, null=True)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('rua', models.CharField(blank=True, max_length=150)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('comprovante_residencia', models.BinaryField(blank=True, null=True)),
                ('autodeclaracao_racial', models.BinaryField(blank=True, null=True)),
                ('comprovante_deficiencia', models.BinaryField(blank=True, null=True)),
                ('nome_escola', models.CharField(blank=True, max_length=150)),
                ('tipo_ensino', models.CharField(blank=True, max_length=100)),
                ('cep_escola', models.CharField(blank=True, max_length=10)),
                ('rua_escola', models.CharField(blank=True, max_length=150)),
                ('bairro_escola', models.CharField(blank=True, max_length=100)),
                ('numero_escola', models.CharField(blank=True, max_length=10)),
                ('complemento_escola', models.CharField(blank=True, max_length=100)),
                ('cidade_escola', models.CharField(blank=True, max_length=100)),
                ('estado_escola', models.CharField(blank=True, max_length=2)),
                ('telefone_escola', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone inválido.', regex='^\\+?1?\\d{9,15}$')])),
                ('telefone_responsavel_escola', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone inválido.', regex='^\\+?1?\\d{9,15}$')])),
                ('password_needs_reset', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('funcao', models.CharField(choices=[('estudante', 'Estudante'), ('professora', 'Professora'), ('admin', 'Admin'), ('avaliadora', 'Avaliadora')], default='estudante', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('deficiencias', models.ManyToManyField(blank=True, to='users.deficiencia')),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.genero')),
                ('raca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.raca')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historico_escolar', models.FileField(blank=True, null=True, upload_to='', verbose_name='Upload do histórico escolar')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.PositiveSmallIntegerField(choices=[(1, '1º'), (2, '2º'), (3, '3º'), (4, '4º')], verbose_name='Bimestre')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Valor da Nota')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.disciplina')),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='users.historicoescolar')),
            ],
            options={
                'unique_together': {('historico', 'disciplina', 'bimestre')},
            },
        ),
    ]
