# Generated by Django 5.2.1 on 2025-08-06 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='funcao',
            field=models.CharField(choices=[('estudante', 'Estudante'), ('professora', 'Professora'), ('admin', 'Admin'), ('avaliadora', 'Avaliadora')], default='estudante', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='telefone_responsavel',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Telefone inválido.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone'),
        ),
    ]
