# Generated by Django 5.2.1 on 2025-05-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_senha_user_groups_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_needs_reset',
            field=models.BooleanField(default=False),
        ),
    ]
