# Generated by Django 5.2.1 on 2025-08-07 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_funcao_user_telefone_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historico_escolar', models.FileField(blank=True, null=True, upload_to='', verbose_name='Upload do histórico escolar')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.PositiveSmallIntegerField(choices=[(1, '1º'), (2, '2º'), (3, '3º'), (4, '4º')], verbose_name='Bimestre')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Valor da Nota')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.disciplina')),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='users.historicoescolar')),
            ],
            options={
                'unique_together': {('historico', 'disciplina', 'bimestre')},
            },
        ),
    ]
