# Generated by Django 5.2.1 on 2025-05-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_password_needs_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(default=12345678910, max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
