# Generated by Django 5.2.1 on 2025-07-18 15:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_projectstatuslog_status_anterior_display_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente', 'Pendente'), ('avaliacao', 'Em Avaliacao'), ('deferida', 'Deferida'), ('indeferida', 'indeferida')], default='rascunho', max_length=10)),
                ('como_soube_programa', models.TextField(blank=True)),
                ('telefone_responsavel', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone inválido.', regex='^\\+?1?\\d{9,15}$')])),
                ('observacoes', models.TextField(blank=True)),
                ('curriculo_lattes_url', models.URLField(blank=True)),
                ('cota_desejada', models.CharField(blank=True, max_length=100)),
                ('tipo_deficiencia', models.CharField(blank=True, max_length=200)),
                ('necessita_material_especial', models.BooleanField(default=False)),
                ('tipo_material_necessario', models.TextField(blank=True)),
                ('laudo_medico_deficiencia', models.BinaryField(blank=True, null=True)),
                ('concorrer_reserva_vagas', models.BooleanField(default=False)),
                ('autodeclaracao_racial', models.BinaryField(blank=True, null=True)),
                ('mulher_trans', models.BooleanField(default=False)),
                ('boletim_escolar', models.BinaryField(blank=True, null=True)),
                ('termo_autorizacao', models.BinaryField(blank=True, null=True)),
                ('rg_frente', models.BinaryField(blank=True, null=True)),
                ('rg_verso', models.BinaryField(blank=True, null=True)),
                ('cpf_anexo', models.BinaryField(blank=True, null=True)),
                ('declaracao_vinculo', models.BinaryField(blank=True, null=True)),
                ('documentacao_comprobatoria_lattes', models.BinaryField(blank=True, null=True)),
                ('perfil_academico', models.CharField(blank=True, max_length=150)),
                ('docencia_superior', models.CharField(blank=True, max_length=150)),
                ('docencia_medio', models.CharField(blank=True, max_length=150)),
                ('orientacao_ic', models.CharField(blank=True, max_length=150)),
                ('feira_ciencias', models.BooleanField(default=False)),
                ('livro_publicado', models.BooleanField(default=False)),
                ('capitulo_publicado', models.BooleanField(default=False)),
                ('periodico_indexado', models.BooleanField(default=False)),
                ('anais_congresso', models.BooleanField(default=False)),
                ('curso_extensao', models.BooleanField(default=False)),
                ('curso_capacitacao', models.BooleanField(default=False)),
                ('orientacoes_estudantes', models.BooleanField(default=False)),
                ('participacoes_bancas', models.BooleanField(default=False)),
                ('apresentacao_oral', models.BooleanField(default=False)),
                ('premiacoes', models.BooleanField(default=False)),
                ('missao_cientifica', models.BooleanField(default=False)),
                ('aceite_declaracao_veracidade', models.BooleanField(default=False)),
                ('aceite_requisitos_tecnicos', models.BooleanField(default=False)),
                ('portugues', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota em Português')),
                ('matematica', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota em Matemática')),
                ('biologia', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota em Biologia')),
                ('quimica', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota em Química')),
                ('fisica', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota em Física')),
                ('historia', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota em História')),
                ('geografia', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota em Geografia')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=10, null=True)),
                ('status_novo', models.CharField(max_length=10)),
                ('status_anterior_display', models.CharField(blank=True, max_length=50, null=True)),
                ('status_novo_display', models.CharField(max_length=50)),
                ('modificado_por', models.CharField(blank=True, max_length=255, null=True, verbose_name='Modificado por (nome e e-mail)')),
                ('data_modificacao', models.DateTimeField(auto_now_add=True)),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_status', to='applications.application')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='AcompanhamentoProjeto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('frequencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status_projeto', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('incompleto', 'Incompleto')], default='em_andamento', max_length=20)),
                ('projeto_entregue', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Acompanhamentos de Projeto',
                'unique_together': {('participante', 'projeto')},
            },
        ),
    ]
