# Generated by Django 5.2.1 on 2025-05-18 17:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente', 'Pendente'), ('deferida', 'Deferida'), ('indeferida', 'indeferida')], default='rascunho', max_length=10)),
            ],
        ),
    ]
