# Generated by Django 5.2.1 on 2025-07-18 17:38

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcompanhamentoProjeto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('frequencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status_projeto', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('incompleto', 'Incompleto')], default='em_andamento', max_length=20)),
                ('projeto_entregue', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Acompanhamentos de Projeto',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('aprovado', models.BooleanField(default=False, help_text='Indica se a candidata foi aprovada no processo seletivo', verbose_name='Aprovada para participação')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente', 'Pendente'), ('avaliacao', 'Em Avaliação'), ('deferida', 'Deferida'), ('indeferida', 'Indeferida')], default='rascunho', max_length=10, verbose_name='Status')),
                ('como_soube_programa', models.TextField(blank=True, verbose_name='Como soube do programa?')),
                ('telefone_responsavel', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone inválido.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone da responsável')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('curriculo_lattes_url', models.URLField(blank=True, verbose_name='Currículo Lattes (URL)')),
                ('area_atuacao', models.CharField(blank=True, max_length=100, verbose_name='Área de atuação')),
                ('cota_desejada', models.CharField(blank=True, max_length=100, verbose_name='Cota desejada')),
                ('tipo_deficiencia', models.CharField(blank=True, max_length=200, verbose_name='Tipo de deficiência')),
                ('necessita_material_especial', models.BooleanField(default=False, verbose_name='Necessita material especial?')),
                ('tipo_material_necessario', models.TextField(blank=True, verbose_name='Tipo de material necessário')),
                ('laudo_medico_deficiencia', models.BinaryField(blank=True, null=True, verbose_name='Laudo médico de deficiência')),
                ('concorrer_reserva_vagas', models.BooleanField(default=False, verbose_name='Concorrer às vagas reservadas?')),
                ('autodeclaracao_racial', models.BinaryField(blank=True, null=True, verbose_name='Autodeclaração racial')),
                ('mulher_trans', models.BooleanField(default=False, verbose_name='Mulher trans')),
                ('boletim_escolar', models.BinaryField(blank=True, null=True, verbose_name='Boletim escolar')),
                ('termo_autorizacao', models.BinaryField(blank=True, null=True, verbose_name='Termo de autorização')),
                ('rg_frente', models.BinaryField(blank=True, null=True, verbose_name='RG (frente)')),
                ('rg_verso', models.BinaryField(blank=True, null=True, verbose_name='RG (verso)')),
                ('cpf_anexo', models.BinaryField(blank=True, null=True, verbose_name='CPF')),
                ('declaracao_vinculo', models.BinaryField(blank=True, null=True, verbose_name='Declaração de vínculo')),
                ('documentacao_comprobatoria_lattes', models.BinaryField(blank=True, null=True, verbose_name='Documentação Lattes')),
                ('grau_formacao', models.CharField(blank=True, max_length=150, verbose_name='Grau de formação')),
                ('perfil_academico', models.CharField(blank=True, max_length=150, verbose_name='Perfil acadêmico')),
                ('docencia_superior', models.CharField(blank=True, max_length=150, verbose_name='Docência no ensino superior')),
                ('docencia_medio', models.CharField(blank=True, max_length=150, verbose_name='Docência no ensino médio')),
                ('orientacao_ic', models.CharField(blank=True, max_length=150, verbose_name='Orientação de IC')),
                ('feira_ciencias', models.BooleanField(default=False, verbose_name='Participou de feira de ciências?')),
                ('livro_publicado', models.BooleanField(default=False, verbose_name='Livro publicado?')),
                ('capitulo_publicado', models.BooleanField(default=False, verbose_name='Capítulo publicado?')),
                ('periodico_indexado', models.BooleanField(default=False, verbose_name='Periódico indexado?')),
                ('anais_congresso', models.BooleanField(default=False, verbose_name='Anais de congresso?')),
                ('curso_extensao', models.BooleanField(default=False, verbose_name='Curso de extensão?')),
                ('curso_capacitacao', models.BooleanField(default=False, verbose_name='Curso de capacitação?')),
                ('orientacoes_estudantes', models.BooleanField(default=False, verbose_name='Orientações de estudantes?')),
                ('participacoes_bancas', models.BooleanField(default=False, verbose_name='Participações em bancas?')),
                ('apresentacao_oral', models.BooleanField(default=False, verbose_name='Apresentações orais?')),
                ('premiacoes', models.BooleanField(default=False, verbose_name='Premiações?')),
                ('missao_cientifica', models.BooleanField(default=False, verbose_name='Missão científica?')),
                ('titulo_projeto_submetido', models.CharField(blank=True, max_length=255, verbose_name='Título do projeto submetido')),
                ('link_projeto', models.URLField(blank=True, verbose_name='Link para o projeto')),
                ('numero_edicoes_participadas', models.PositiveIntegerField(default=0, verbose_name='Número de edições anteriores do programa')),
                ('aceite_declaracao_veracidade', models.BooleanField(default=False, verbose_name='Aceite da declaração de veracidade')),
                ('aceite_requisitos_tecnicos', models.BooleanField(default=False, verbose_name='Aceite dos requisitos técnicos')),
                ('portugues', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota em Português')),
                ('matematica', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota em Matemática')),
                ('biologia', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota em Biologia')),
                ('quimica', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota em Química')),
                ('fisica', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota em Física')),
                ('historia', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota em História')),
                ('geografia', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota em Geografia')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=10, null=True)),
                ('status_novo', models.CharField(max_length=10)),
                ('status_anterior_display', models.CharField(blank=True, max_length=50, null=True)),
                ('status_novo_display', models.CharField(max_length=50)),
                ('modificado_por', models.CharField(blank=True, max_length=255, null=True, verbose_name='Modificado por (nome e e-mail)')),
                ('data_modificacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
