# Generated by Django 5.2.1 on 2025-08-07 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acompanhamentoprojeto',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acompanhamentoprojeto',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='application',
            name='cota_desejada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.cota', verbose_name='Cota desejada'),
        ),
        migrations.AddField(
            model_name='application',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Projeto'),
        ),
        migrations.AddField(
            model_name='application',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuária'),
        ),
        migrations.AddField(
            model_name='applicationstatuslog',
            name='inscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_status', to='applications.application'),
        ),
        migrations.AddField(
            model_name='applicationstatuslog',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='acompanhamentoprojeto',
            unique_together={('participante', 'projeto')},
        ),
    ]
