# Generated by Django 5.2.1 on 2025-08-08 20:31

from django.db import migrations
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = []

