# Generated by Django 5.2.1 on 2025-07-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='atividade_docente_pontuacao',
            field=models.FloatField(default=0.0, verbose_name='Pontuação - Atividade Docente'),
        ),
        migrations.AddField(
            model_name='application',
            name='atividade_pesquisa_pontuacao',
            field=models.FloatField(default=0.0, verbose_name='Pontuação - Atividade de Pesquisa'),
        ),
        migrations.AddField(
            model_name='application',
            name='outras_atividades_pontuacao',
            field=models.FloatField(default=0.0, verbose_name='Pontuação - Outras Atividades'),
        ),
        migrations.AddField(
            model_name='application',
            name='perfil_academico_pontuacao',
            field=models.FloatField(default=0.0, verbose_name='Pontuação - Perfil Acadêmico'),
        ),
        migrations.AddField(
            model_name='application',
            name='ranking',
            field=models.FloatField(blank=True, null=True, verbose_name='Pontuação total (ranking)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='docencia_medio',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Docência no ensino médio'),
        ),
        migrations.AlterField(
            model_name='application',
            name='docencia_superior',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Docência no ensino superior'),
        ),
        migrations.AlterField(
            model_name='application',
            name='grau_formacao',
            field=models.CharField(blank=True, choices=[('graduacao', 'Graduação (Bacharelado ou Licenciatura)'), ('licenciatura', 'Licenciatura (específica)'), ('bacharelado', 'Bacharelado (específico)'), ('tecnologo', 'Tecnólogo'), ('especializacao', 'Especialização'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado'), ('pos_doutorado', 'Pós-doutorado'), ('outro', 'Outro')], help_text='Informe o grau de formação mais alto concluído', max_length=20, null=True, verbose_name='Grau de formação mais alto'),
        ),
        migrations.AlterField(
            model_name='application',
            name='orientacao_ic',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Orientação de IC'),
        ),
    ]
