# Generated by Django 5.2.1 on 2025-08-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20250808_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='link_projeto',
            field=models.URLField(blank=True, null=True, verbose_name='Link para o projeto'),
        ),
        migrations.AlterField(
            model_name='application',
            name='perfil_academico',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Perfil acadêmico'),
        ),
        migrations.AlterField(
            model_name='application',
            name='titulo_projeto_submetido',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título do projeto submetido'),
        ),
    ]
