# Generated by Django 5.2.1 on 2025-05-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente', 'Pendente'), ('avaliacao', 'Em Avaliacao'), ('deferida', 'Deferida'), ('indeferida', 'indeferida')], default='rascunho', max_length=10),
        ),
    ]
