# Generated by Django 5.2.1 on 2025-08-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_link_projeto_and_more'),
    ]

    operations = []
