# Generated by Django 5.2.1 on 2025-08-08 21:25

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20250808_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='tipo_deficiencia',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=models.SET_NULL,
                to='users.Deficiencia',
                verbose_name='Tipo de deficiência'
            ),
        ),
    ]
