# Generated by Django 5.2.1 on 2025-08-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='drive_boletim_escolar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID do boletim escolar no Drive'),
        ),
        migrations.AddField(
            model_name='application',
            name='drive_cpf_anexo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID do CPF no Drive'),
        ),
        migrations.AddField(
            model_name='application',
            name='drive_declaracao_vinculo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da declaração de vínculo no Drive'),
        ),
        migrations.AddField(
            model_name='application',
            name='drive_documentacao_comprobatoria_lattes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da documentação Lattes no Drive'),
        ),
        migrations.AddField(
            model_name='application',
            name='drive_rg_frente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID do RG (frente) no Drive'),
        ),
        migrations.AddField(
            model_name='application',
            name='drive_rg_verso',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID do RG (verso) no Drive'),
        ),
        migrations.AddField(
            model_name='application',
            name='drive_termo_autorizacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID do termo de autorização no Drive'),
        ),
    ]
