# Generated by Django 5.2.1 on 2025-05-17 15:37

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('criado_por', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Criado por (e-mail)')),
                ('atualizado_por', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Atualizado por (e-mail)')),
                ('eh_remoto', models.BooleanField(default=False, verbose_name='É remoto')),
                ('regioes_aceitas', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('NORTE', 'Norte'), ('NORDESTE', 'Nordeste'), ('CENTRO-OESTE', 'Centro-Oeste'), ('SUDESTE', 'Sudeste'), ('SUL', 'Sul')], max_length=20), default=list, size=None, verbose_name='Regiões aceitas')),
                ('formato', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto')], default='presencial', max_length=20, verbose_name='Formato')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('inscricoes_abertas', 'Inscrições Abertas'), ('avaliacao_inscricoes', 'Avaliação das Inscrições'), ('inscricoes_aprovadas', 'Inscrições Aprovadas'), ('em_andamento', 'Em Andamento'), ('avaliacao_projeto', 'Avaliação do Projeto'), ('finalizado', 'Finalizado')], default='rascunho', max_length=30, verbose_name='Status')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de fim')),
                ('vagas', models.PositiveIntegerField(verbose_name='Vagas')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
    ]
