# Generated by Django 5.2.1 on 2025-07-18 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tutora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_tutorados', to=settings.AUTH_USER_MODEL, verbose_name='Tutora'),
        ),
        migrations.AddField(
            model_name='projectstatuslog',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_status', to='projects.project'),
        ),
    ]
