# Generated by Django 5.2.1 on 2025-05-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cidades_aceitas',
            field=models.ManyToManyField(blank=True, related_name='projetos', to='core.cidade', verbose_name='Cidades aceitas'),
        ),
        migrations.AddField(
            model_name='project',
            name='estados_aceitos',
            field=models.ManyToManyField(blank=True, related_name='projetos', to='core.estado', verbose_name='Estados aceitos'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='regioes_aceitas',
        ),
        migrations.AddField(
            model_name='project',
            name='regioes_aceitas',
            field=models.ManyToManyField(blank=True, related_name='projetos', to='core.regiao', verbose_name='Regiões aceitas'),
        ),
    ]
