# Generated by Django 5.2.1 on 2025-07-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='data_divulgacao_resultado',
            field=models.DateField(blank=True, null=True, verbose_name='Data de divulgação do resultado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='data_fim',
            field=models.DateField(verbose_name='Data de fim'),
        ),
        migrations.AlterField(
            model_name='project',
            name='data_ifm',
            field=models.DateField(blank=True, null=True, verbose_name='Data do IFM (Início da Formação de Monitoras)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='project',
            name='data_inicio_projeto',
            field=models.DateField(blank=True, null=True, verbose_name='Data prevista de início do projeto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='fim_inscricoes',
            field=models.DateField(verbose_name='Fim das inscrições'),
        ),
        migrations.AlterField(
            model_name='project',
            name='formato',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Hibrido')], default='presencial', max_length=20, verbose_name='Formato'),
        ),
        migrations.AlterField(
            model_name='project',
            name='inicio_inscricoes',
            field=models.DateField(verbose_name='Início das inscrições'),
        ),
    ]
