# Generated by Django 5.2.1 on 2025-05-18 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='importacoes/')),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('linhas_lidas', models.IntegerField(default=0)),
                ('projetos_criados', models.IntegerField(default=0)),
                ('projetos_ignorados', models.IntegerField(default=0)),
                ('linhas_ignoradas_texto', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='fim_inscricoes',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fim das inscrições'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='inicio_inscricoes',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Início das inscrições'),
            preserve_default=False,
        ),
    ]
